// Code generated by ogen, DO NOT EDIT.
package ogent

type CreateCardRes interface {
	createCardRes()
}

type CreateGroupRes interface {
	createGroupRes()
}

type CreateUserRes interface {
	createUserRes()
}

type DeleteCardRes interface {
	deleteCardRes()
}

type DeleteGroupRes interface {
	deleteGroupRes()
}

type DeleteUserRes interface {
	deleteUserRes()
}

type ListCardRes interface {
	listCardRes()
}

type ListGroupRes interface {
	listGroupRes()
}

type ListGroupUsersRes interface {
	listGroupUsersRes()
}

type ListUserCardRes interface {
	listUserCardRes()
}

type ListUserRes interface {
	listUserRes()
}

type ReadCardOwnerRes interface {
	readCardOwnerRes()
}

type ReadCardRes interface {
	readCardRes()
}

type ReadGroupRes interface {
	readGroupRes()
}

type ReadUserRes interface {
	readUserRes()
}

type UpdateCardRes interface {
	updateCardRes()
}

type UpdateGroupRes interface {
	updateGroupRes()
}

type UpdateUserRes interface {
	updateUserRes()
}
