// Code generated by ogen, DO NOT EDIT.
package ogent

type CreateUsersRes interface {
	createUsersRes()
}

type DeleteUsersRes interface {
	deleteUsersRes()
}

type ListUsersRes interface {
	listUsersRes()
}

type ReadUsersRes interface {
	readUsersRes()
}

type UpdateUsersRes interface {
	updateUsersRes()
}
